version: '3'
services:
  app:
    container_name: go-xapiens-api
    build: .
    ports: 
      - 8002:8002 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - xapiens-postgres          
    networks:
      - xapiens


  xapiens-postgres:
    image: postgres:latest
    container_name: go-xapiens-db
    environment:
      - POSTGRES_USER=${db_user}  
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_DB=${db_name}
      - DATABASE_HOST=${db_host} 
    ports:
      - '5433:5433'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - xapiens
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - xapiens-postgres
    ports:
      - "5050:80"
    networks:
      - xapiens
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  xapiens:
    driver: bridge